apiVersion: projectriff.io/v1
kind: Topic
metadata:
  name: function-replicas
---

apiVersion: projectriff.io/v1
kind: Function
metadata:
  name: vote-stream-processor
spec:
  protocol: pipes
  input: votes
  output: function-replicas
  maxReplicas: 1
  idleTimeoutMs: 60000
  container:
    image: projectriff/vote-stream-processor:1.0.0
    env:
    - name: SPRING_CLOUD_STREAM_BINDER_FILE_PREFIX
      value: /pipes
    - name: SPRING_APPLICATION_JSON
      value: '{"logging.level.org.springframework.cloud.stream.binder.file":"DEBUG", "spring.cloud.stream.bindings.output.content-type":"application/json"}'
