apiVersion: projectriff.io/v1
kind: Topic
metadata:
  name: words
---

apiVersion: projectriff.io/v1
kind: Topic
metadata:
  name: counts
---

apiVersion: projectriff.io/v1
kind: Function
metadata:
  name: word-counter
spec:
  protocol: http
  input: words
  output: counts
  container:
    image: projectriff/word-counter:1.0.0
    env:
    - name: SPRING_CLOUD_STREAM_BINDER_FILE_PREFIX
      value: /pipes
    - name: SPRING_APPLICATION_JSON
      value: '{"logging.level.org.springframework.cloud.stream.binder.file":"DEBUG"}'
