apiVersion: projectriff.io/v1
kind: Function
metadata:
  name: word-counter-redis-writer
spec:
  protocol: http
  input: word-counts
  container:
    image: projectriff/redis-writer:1.0.0
    env:
    - name: DEFAULT_HASH_KEY
      value: demo:word-counts
    - name: DEFAULT_COMMAND
      value: increment
    - name: REDIS_PASSWORD
      valueFrom:
        secretKeyRef:
          name: counters-redis
          key: redis-password
