apiVersion: projectriff.io/v1
kind: Topic
metadata:
  name: votes
spec:
  partitions: 10
---
apiVersion: projectriff.io/v1
kind: Topic
metadata:
  name: counted-votes
spec:
  partitions: 1
---
apiVersion: projectriff.io/v1
kind: Function
metadata:
  name: vote-counter
spec:
  protocol: grpc
  input: votes
  output: counted-votes
  idleTimeoutMs: 5000
  container:
    image: projectriff/vote-counter:0.0.5-snapshot-3-15-b
    env:
    - name: NODE_DEBUG
      value: riff
    - name: REDIS_PASSWORD
      valueFrom:
        secretKeyRef:
          name: counters-redis
          key: redis-password
