apiVersion: projectriff.io/v1
kind: Topic
metadata:
  name: vote-interval-counts
---

apiVersion: projectriff.io/v1
kind: Function
metadata:
  name: vote-interval-writer
spec:
  protocol: http
  input: vote-interval-counts
  idleTimeoutMs: 30000
  container:
    image: projectriff/redis-writer:1.0.0
    env:
    - name: LIST_KEY
      value: demo:votes-log
    - name: REDIS_HOST
      value: counters-redis.default.svc.cluster.local
    - name: REDIS_PASSWORD
      valueFrom:
        secretKeyRef:
          name: counters-redis
          key: redis-password
