apiVersion: projectriff.io/v1
kind: Topic
metadata:
  name: votes
spec:
  partitions: 3
---

apiVersion: projectriff.io/v1
kind: Function
metadata:
  name: vote-counter
spec:
  protocol: http
  input: votes
  idleTimeoutMs: 30000
  container:
    image: projectriff/redis-writer:1.0.0
    env:
    - name: DEFAULT_HASH_KEY
      value: demo:votes
    - name: REDIS_HOST
      value: counters-redis.default.svc.cluster.local
    - name: REDIS_PASSWORD
      valueFrom:
        secretKeyRef:
          name: counters-redis
          key: redis-password
